#!/usr/bin/env bash
# In-VM: generate art/dalvikvm/static_jni_symbols.cpp — the table of Java_*
# symbols exported by the statically linked boot JNI libraries, used by the
# fully static dalvikvms for lazy native-method resolution (no dlsym in a
# static binary). Two-pass: needs the static archives built first; writes a
# stub table when they are absent so soong analysis always succeeds.
# Idempotent (content-hash stable).
set -euo pipefail

AOSP=/opt/aosp/main-art
NM=$AOSP/prebuilts/clang/host/linux-arm64/clang-r584948b/bin/llvm-nm
OUT_CPP=$AOSP/art/dalvikvm/static_jni_symbols.cpp
I=$AOSP/out/soong/.intermediates
VARIANT=linux_musl_arm64_static

ARCHIVES=()
for mod in \
  libcore/libjavacore_static \
  libcore/libopenjdk_static \
  art/openjdkjvm/libopenjdkjvm_static \
  external/icu/android_icu4j/libcore_bridge/src/native/libicu_jni_static \
  external/conscrypt/libjavacrypto_static; do
  a="$I/$mod/$VARIANT/$(basename "$mod").a"
  [ -f "$a" ] && ARCHIVES+=("$a")
done

emit() {
  {
    echo "// Generated by art-host scripts/56-gen-static-jni-symbols.sh. Do not edit."
    echo "// Table of Java_* symbols in the static boot JNI libs, consumed via the"
    echo "// weak art_static_jni_lookup hook in art/runtime/jni/java_vm_ext.cc."
    echo '#include <cstring>'
    echo
    echo 'extern "C" {'
    for s in "$@"; do echo "void $s();"; done
    echo '}'
    echo
    echo 'namespace {'
    echo 'struct Sym { const char* name; void* fn; };'
    echo 'const Sym kSyms[] = {'
    for s in "$@"; do echo "    {\"$s\", reinterpret_cast<void*>($s)},"; done
    echo '};'
    echo '}  // namespace'
    echo
    echo 'extern "C" void* art_static_jni_lookup(const char* name) {'
    echo '  for (const Sym& s : kSyms) {'
    echo '    if (std::strcmp(s.name, name) == 0) {'
    echo '      return s.fn;'
    echo '    }'
    echo '  }'
    echo '  return nullptr;'
    echo '}'
  } > "$OUT_CPP.tmp"
  if ! cmp -s "$OUT_CPP.tmp" "$OUT_CPP" 2>/dev/null; then
    mv "$OUT_CPP.tmp" "$OUT_CPP"
    echo "wrote $OUT_CPP ($# symbols)"
  else
    rm "$OUT_CPP.tmp"
    echo "unchanged ($# symbols)"
  fi
}

if [ ${#ARCHIVES[@]} -eq 0 ]; then
  echo "no static archives yet; writing stub table"
  emit
else
  # shellcheck disable=SC2046
  emit $("$NM" -g --defined-only "${ARCHIVES[@]}" | awk '$2 == "T" && $3 ~ /^Java_/ {print $3}' | sort -u)
fi
echo "56-gen-static-jni-symbols: OK"
